'use client'
import type { Metadata } from 'next'
import Header from '@/components/modules/Header/Header'
import Footer from '@/components/modules/Footer/Footer'

export const metadata: Metadata = {
	title: 'Tools Store',
	description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
	return (
		<>
			<Header />
			{children}
			<Footer />
		</>
	)
}